/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260311T205057"   // DateTime using ISO-8601 format
        " "                 // alignment
        "a322e7d3"          // STLIB commit
        "--------"          // ADJ commit
        "1c2d00a7"          // Board commit
        // the '=' is used for unparsing
        ;
}