/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260304T233026"   // DateTime using ISO-8601 format
        " "                 // alignment
        "b7764b10"          // STLIB commit
        "--------"          // ADJ commit
        "d4afa07e"          // Board commit
        // the '=' is used for unparsing
        ;
}